### ISSUE TITLE
installation by composer ?

### ISSUE THREAD

**Issue by ghost** [ZF-Commons/ZfcAcl#17]
Hi there, it would be great to install zf-acl module by composer

David

**Comment by matuszeman** [comment]
Hi David,
It would be nice if all the modules has got composer file attached.
Are you able to contribute and submit PR implementing this?

**Comment by ghost** [comment]
Hi Matus,
My english is very poor and i don't knowvery much how to build installer.
But i made a PR to add a composer.json first.
I suppose ZfcAcl package name should be:
zf-commons/zfc-acl

David

**Comment by Ninjadeer** [comment]
Hi I just added this to my local composer.json, Im only just getting to grips with composer as well.

```
"repositories": [
    {
        "type": "package",
        "package": {
            "name": "zf-commons/zfc-acl",
            "version": "dev-master",
            "source": {
                "url": "https://github.com/ZF-Commons/ZfcAcl.git",
                "type": "git",
                "reference": "218b9d7ae5744d26140b2bc147221a229ac10700"
            },
            "autoload": {
                "psr-0": {
                    "ZfcAcl": "src/"
                },
                "classmap": [
                    "./"
                ]
            }
        }
    }
}
```

**Comment by ghost** [comment]
To build the package : http://packagist.org/

**Comment by matuszeman** [comment]
Hi there,
composer.json has been added into the module root folder.
Could you try to install it? http://packagist.org/packages/zf-commons/zfc-acl
Unfortunately I registered it using git@github.com:ZF-Commons/ZfcAcl.git instead of git://github.com/ZF-Commons/ZfcAcl.git so I just hope it's going to work for you. I've contacted packagist guys to fix it for us.
Matus

**Comment by ghost** [comment]
It works fine!
Thank you

**Comment by matuszeman** [comment]
This is the problem I expected... it was a mistake on my side submitting
read/write repo URL.
Unfortunately I'm not able to change repository URL  http://packagist.org/ yet.
This is still under pending work:
https://github.com/composer/packagist/issues/110 .
I've tried to contact them asking for "quickfix" - we'll need to wait
unfortunately.

Matus

On Wed, May 30, 2012 at 11:01 AM, david quintard <
reply@reply.github.com

**Comment by davidwindell** [comment]
Any update on this one? Is there an alternative in the meantime?

**Comment by matuszeman** [comment]
There is... Fork ZfcAcl and submit your repo URL to http://packagist.org as this guy did - http://packagist.org/packages/wesrc/zfc-acl. Or just use his if it's being updated regularly.
