### ISSUE TITLE
Move route guard to 'route' event

### ISSUE THREAD

**Issue by Ocramius** [ZF-Commons/ZfcAcl#5]
Currently, the route guard listens to the `dispatch` event with a priority of `1000`. Even if this works, it is incorrect. The route guard should probably listen to the `route` event with priority `-1000`.

**Comment by matuszeman** [comment]
done

**Comment by Ocramius** [comment]
For reference, f0e0e20938fac84fe2a10e4cf35c2039032fa6a2
